/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logica.CerrarJF;
import Logica.Operaciones;
import Logica.Validaciones;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author israe
 */
public class DialogoOperacines extends javax.swing.JFrame {

    /**
     * Creates new form DialogoOperacines
     */
    
    public boolean estado;
    

    public DialogoOperacines(boolean estadoDialogo) {
        this.estado = estadoDialogo;
    }
    
    public DialogoOperacines() {
        initComponents();
    }

    public boolean isEstadoDialogo() {
        return estado;
    }

    public void setEstadoDialogo(boolean estadoDialogo) {
        this.estado = estadoDialogo;
    }
    
    
    CerrarJF cjf = new CerrarJF(this);// instacia de clase para cerra jfrem desde cual quier clase

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBorderGUI1 = new GUI.JBorderGUI();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btbCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(237, 237, 237));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(44, 44, 44));
        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jLabel1.setText("Confirmar Operacion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 192, 30));

        btbCancelar.setBackground(new java.awt.Color(250, 76, 76));
        btbCancelar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btbCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btbCancelar.setText("Cancelar");
        btbCancelar.setPreferredSize(new java.awt.Dimension(116, 40));
        btbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        btnConfirmar.setBackground(new java.awt.Color(0, 117, 250));
        btnConfirmar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confimar");
        btnConfirmar.setPreferredSize(new java.awt.Dimension(116, 40));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        javax.swing.GroupLayout jBorderGUI1Layout = new javax.swing.GroupLayout(jBorderGUI1);
        jBorderGUI1.setLayout(jBorderGUI1Layout);
        jBorderGUI1Layout.setHorizontalGroup(
            jBorderGUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        jBorderGUI1Layout.setVerticalGroup(
            jBorderGUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBorderGUI1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBorderGUI1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
// TODO add your handling code here
        
        try {
            
            Operaciones.OpRegitrarEntrara();
            dispose();
            System.exit(0);
            
        } catch (SQLException | FileNotFoundException ex) {
            Logger.getLogger(DialogoOperacines.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
      
        
    }//GEN-LAST:event_btbCancelarActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbCancelar;
    private javax.swing.JButton btnConfirmar;
    private GUI.JBorderGUI jBorderGUI1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
